# Copyright (c) 2026, Arka Mondal. All rights reserved.
# Use of this source code is governed by a BSD-style license that
# can be found in the LICENSE file.

# Top-level (project-root) build.

NAME := av6
KNAME := AV6
# CODENAME := jumping-jellyfish

CROSS ?= aarch64-linux-gnu
CC := $(CROSS)-gcc
LD := $(CROSS)-ld
OBJCOPY := $(CROSS)-objcopy

SRCDIR := src

BUILDROOT := build
BUILDDIR := $(BUILDROOT)$(if $(KTEST),-ktest)$(if $(NODEBUG),-nodebug)

INCLDIR := $(SRCDIR)/include
USERDIR := $(SRCDIR)/user

# Kernel source subsystem dirs
SRCSUBDIRS := arch vm kern dev libkern

ifdef KTEST
SRCSUBDIRS += tests
endif

# Build verbosity : make V=1 shows full commands. default prints terse tags
# E prints a tag line, Q quietens the actual command
ifeq ($(V),1)
Q :=
E := @:
else
Q := @
E := @echo
endif

NCPU_MAX ?= 32

CONFIG_H := $(BUILDDIR)/include/av6_config.h
ASSYM_S := $(BUILDDIR)/include/assym.s

CFLAGS := -Wall -Wextra -ffreestanding -nostdlib -mgeneral-regs-only \
			-march=armv9-a+memtag -I $(INCLDIR) -I $(BUILDDIR)/include \
			-include av6_config.h -MMD -MP
LDFLAGS := -nostdlib -T $(SRCDIR)/kernel.ld --defsym=NCPU_MAX=$(NCPU_MAX)

BINNAME := $(BUILDDIR)/$(NAME).bin
ELFNAME := $(BUILDDIR)/$(NAME).elf

KSRC_C := $(wildcard $(addprefix $(SRCDIR)/,$(addsuffix /*.c,$(SRCSUBDIRS))))
KSRC_S := $(wildcard $(addprefix $(SRCDIR)/,$(addsuffix /*.s,$(SRCSUBDIRS))))
KOBJS_S := $(KSRC_S:$(SRCDIR)/%.s=$(BUILDDIR)/%.o)
KOBJS := $(KSRC_C:$(SRCDIR)/%.c=$(BUILDDIR)/%.o) $(KOBJS_S)
KDEPS := $(KSRC_C:$(SRCDIR)/%.c=$(BUILDDIR)/%.d)

$(CONFIG_H) : FORCE
	@mkdir -p $(@D)
	@{                                                                          \
		echo '/* Generated by the Makefile -- do not edit. */';                 \
		echo '#ifndef _AV6_CONFIG_H_';                                          \
		echo '#define _AV6_CONFIG_H_';                                          \
		echo '';                                                                \
		$(if $(KTEST),echo '#define AV6_KTEST               1';)                \
		$(if $(KTEST_ONLY),echo '#define KTEST_ONLY         "$(KTEST_ONLY)"';)  \
		$(if $(SCENARIO),echo '#define KTEST_SCENARIO_NAME  "$(SCENARIO)"';)    \
		$(if $(NODEBUG),,echo '#define AV6_INVARIANTS          1';)             \
		echo '#define NCPU_MAX             $(NCPU_MAX)';                        \
		echo '';                                                                \
		echo '#endif';                                                          \
	} > $@.tmp
	@if cmp -s $@ $@.tmp; then rm -f $@.tmp;    \
	else echo '  CONFIG    $@'; mv -f $@.tmp $@; fi

$(ASSYM_S) : $(INCLDIR)/arch/assym.h
	@mkdir -p $(@D)
	$(E) '  GEN       $@'
	@echo '/* Generated from arch/assym.h -- do not edit. */' > $@
	@sed -n 's|^#define[[:space:]]\{1,\}\([A-Z_0-9]\{1,\}\)[[:space:]]\{1,\}\([0-9]\{1,\}\)[[:space:]]*\(/\*.*\)\{0,1\}$$|.equ \1, \2|p' $< >> $@

# Order-only: the header must exist before the first compile. After than the .d
# files carry the real dependency, and that is what triggers rebuilds.
$(KOBJS) : | $(CONFIG_H) $(ASSYM_S)

$(KOBJS_S) : $(ASSYM_S)

# Userland rules (defines USER_BLOB user $(BUILDDIR)/user). Included, not recursed.
include $(USERDIR)/user.mk

# Default goal: wrap the build so it always ends with an explicit ready/FAILED
# line. -s (unless V=1) hides make's own chatter. The $(E) tags still print.
.DEFAULT_GOAL := build

build :
	@$(MAKE) $(if $(filter 1,$(V)),, -s) --no-print-directory $(BINNAME) \
	        && echo '  BUILD   $(BINNAME)  ready' \
			|| { echo '  BUILD   FAILED'; exit 1; }

all : $(BINNAME)

$(BINNAME) : $(ELFNAME)
	$(E) '  OBJCOPY   $@'
	$(Q)$(OBJCOPY) -O binary $< $@

$(ELFNAME) : $(KOBJS) $(USER_BLOB) $(SRCDIR)/kernel.ld
	$(E) '  LD        $@'
	$(Q)$(LD) $(LDFLAGS) -o $@ $(KOBJS) $(USER_BLOB)

$(BUILDDIR)/%.o : $(SRCDIR)/%.c
	@mkdir -p $(dir $@)
	$(E) '  CC        $@'
	$(Q)$(CC) $(CFLAGS) -o $@ -c $<

$(BUILDDIR)/%.o : $(SRCDIR)/%.s
	@mkdir -p $(dir $@)
	$(E) '  AS        $@'
	$(Q)$(CC) $(CFLAGS) -o $@ -c $<

-include $(KDEPS)

.PHONY : all build clean distclean run check check-run FORCE
.DELETE_ON_ERROR :

clean : RMDIRS := $(BUILDDIR)
distclean : RMDIRS := $(BUILDROOT) $(wildcard $(BUILDROOT)-*)

clean distclean :
	$(E) '  CLEAN   $(RMDIRS)'
	$(Q)rm -rf $(RMDIRS)

# QEMU run configuration (override on command list: make run CPUS=2 MEM=4)
# QEMU : emulator binary
# CPUS : virtual CPU count (-smp)
# MEM : RAM in GiB (-m)
QEMU ?= qemu-system-aarch64
CPUS ?= 4
MEM ?= 1

run: build
	$(E) '  BOOT    $(BINNAME)'
	$(E) 'BOOTING  $(KNAME)  (smp=$(CPUS) mem=$(MEM)G)'
	$(Q)$(QEMU) -M virt,mte=on,gic-version=3 -cpu neoverse-n2 -smp $(CPUS) -m $(MEM)G -nographic -kernel $(BINNAME)

# Boot a KTEST=1 kernel and let the host judge the KTRF it printed.
check:
	$(Q)$(MAKE) KTEST=1 --no-print-directory check-run

# Internal
check-run: build
	$(Q)test -n "$(KTEST)" || { echo '  check-run is internal, use: make check'; exit 1; }
	$(Q)tools/runtests.sh $(if $(SCENARIO),--scenario $(SCENARIO)) $(BINNAME) $(CPUS) $(MEM)
